<?php

namespace SiteBundle\Repository;

/**
 * HinoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HinoRepository extends \Doctrine\ORM\EntityRepository
{
}
